### PR TITLE
Added mintupdate style class to the window for easier theming

### PR DESCRIPTION
**Pull request by Toshayo**
This is the second part of https://github.com/linuxmint/mintupdate/pull/815

### CODE REVIEW

**Comment by Toshayo** [comment]
If you would like me to port the changes to other branches, just tell it ;)

**Comment by anaximeno** [comment]
@Toshayo I am not sure but feature updates are made only on master. Other branches, especially maintenance ones, primarily receive fixes.

**Comment by Toshayo** [comment]
It sounds quite logical, should i close the PR?

**Comment by mtwebster** [comment]
I'll close, the other is merged.

**Pull request closed without merging**
