### PR TITLE
Translation: fetch some strings with ngettext

### PR DESCRIPTION
**Pull request by NikoKrause**
fixes https://github.com/linuxmint/mintupdate/issues/110

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @NikoKrause,

Some of the msgids could be simplified to avoid using ngettext... 

To be honest, I know we need ngettext, but I'd like to avoid it as much as possible in Python. The reason for this is that argument mismatches will make Python crash, whereas they're perfectly OK in C.

For instance, if "%d update", "%d updates" is translated into "%d mise a jour" and "%d mises a jour" in French, that will work both in C and in Python... but if it gets translated into "1 mise a jour" and "%d mises a jour"... that will work in C but will crash the app in Python.

I'd like mint-translations's mocheck to detect this actually... at the moment it doesn't warn for argument mismatches like these because they're OK in C (and we've plenty of them in our C translations).

We should detect the fact that we're dealing with either C or Python and adapt mocheck to warn for Python but not for C.

This is really important if we start allowing ngettext translations in Python.

OK, with all that said... 

- I simplified some msgids on master to avoid the need for ngettext.
- Please rebase to take this into account
- Please remove/checkout mintupdate.pot from your PR (this is used to detect changes and the need to upload to LP, so it shouldn't be modified in PRs really)
- If you get the chance to look into mocheck (in mint-translations), please do..  :) I'll have a look otherwise but I'm not sure I can do it this week.

**Comment by NikoKrause** [comment]
It's pretty bad translated, if someone translate %d to 1.

If I find time I look into mocheck.

**Comment by clefebvre** [comment]
It happens all the time... and in the context of a C ngettext translation, translating %d into 1 for n=1 is perfectly OK.

**Comment by NikoKrause** [comment]
What do you think of writing a custom ngettext function for Python, which catches mismatches?
Not sure if it's possible?

**Comment by NikoKrause** [comment]
I think the problem you describe is this?
https://github.com/python-babel/flask-babel/issues/27#issuecomment-32446371

Would this work?

**Comment by NikoKrause** [comment]
This issue is also described here:
https://bugs.launchpad.net/ubuntu/+source/system-config-printer/+bug/214732

They suggest to use `msgfmt --check-format` to detect such mismatches.

I tried to look at mocheck, but it's far too big for me right now to dig deeper. Sorry

**Comment by clefebvre** [comment]
Hi @NikoKrause, I made the necessary changes in mocheck so you can now use ngettext in python projects. Please rebase and adapt your PR.

**Comment by NikoKrause** [comment]
rebased

**Pull request merged**
