### PR TITLE
Show changelog from PPA packages - issue #56

### PR DESCRIPTION
**Pull request by brennanhm**
Hi :)

This is my attempt to display the latest changelog entry for PPA packages. 

If a changelog is not found in the official sources, the code assumes the package comes from a PPA and tries to get the latest changelog entry from Launchpad. 

I have tried using two different methods to get the PPA owner and name, which are required to build the Launchpad URL. The first method, which I've commented out, will throw an exception when issuing the apt-cache command if the package has not been installed. I think the second method is better, but please let me know if there is an easier or more efficient way of doing this. I've tested it successfully with four different Launchpad hosted PPAs. 

This is my first attempt to contribute to the Linux Mint codebase and I am relatively new to Python (and git/Github), so please let me know if you have any feedback...

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi, thanks for contributing :)

In checkAPT.py, check the value of the "origin" for PPA packages. This could be used not only to specify to mintUpdate.py that a particular package is from a PPA, but also which ppa owner/name it belongs to.

**Comment by brennanhm** [comment]
Hi, thanks for the feedback!

I checked the 'origin' value for PPA packages and it seems to separate the words of both the owner and name only using hyphens. Also, the origin of one of the PPA packages on my test machine only contained the owner, but not the name. Without a consistent naming convention, I'm not sure how to make an accurate distinction between the two. Here are a few examples:

**origin:'LP-PPA-mc3man-trusty-media'** (owner: mc3man, name: trusty-media)
**origin:'LP-PPA-otto-kesselgulasch-gimp'** (owner: otto-kesselgulasch, name: gimp)
**origin:'LP-PPA-xorg-edgers'** (owner: xorg-edgers, name: ppa)

For the time being I've left in the grep commands until I can come up with a better solution.

As for the code, I've added two lines to checkAPT.py that will check if the package is indeed from a PPA. In mintUpdate.py an **elif** has been added to check if the package is from a PPA and if so, builds and then appends the Launchpad URL to changelog_sources. In the changelog_sources loop, if the source contains "launchpad.net" the source page is scraped for the change record and then assigned to the changelog variable.

Please let me know if I'm going about getting the PPA name and owner incorrectly and I apologize if I missed something simple :)

**Comment by brennanhm** [comment]
I haven't figured out a way to reliably separate the PPA owner and name without issuing a system command. However, I believe using the 'more' command to pull the information directly from /etc/apt/sources.list.d/ is more efficient and accurate than piping greps together. In sources.list.d the PPA name and owner are separated by forward slashes and can be split with accurate results.

Based on Python's official documentation, I was a little worried about setting shell=True in the check_output() method due to a [security issue](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments), but I don't think it's possible for the input (origin) to contain a malicious command. I'm using a wildcard to complete the source's filename and it won't work without setting shell=True.

I have also moved the elif statement in checkAPT.py to a position that I think makes it more readable.

**Comment by brennanhm** [comment]
The code now loops through the files within the /etc/apt/sources.list.d/ directory and uses the fnmatch() method to identify the correct source file, which is opened and split to capture the PPA owner and name. The shell commands used previously have been replaced with Python fuctions for better efficiency and security. Also, variable assignments are no longer aligned on the '=' character.

Thanks to Eduard Dopler for the feedback.

**Comment by brennanhm** [comment]
I've created a new function, called get_ppa_changelog(), that downloads the PPA package's debian tarball from Launchpad (if one exists) and extracts the full changelog from it. If unsuccessful, it falls back to scraping the latest change record from Launchpad's source.changes file. 

I've imported two additional modules:
**urllib** - To make downloading the debian tarball easier with the urlretrieve() method. 
**tarfile** - To handle decompressing and extracting the changelog from the tarball. Python 2's tarfile module doesn't support .xz compression, so when a *.xz file is retrieved, a shell command is used to decompress it. 

So far, I've been able to test it successfully with four different PPAs.

Thanks to darealshinji for the bash script example :)

**Comment by muzena** [comment]
This don't work if user add PPA sources in /etc/apt/sources.list file or have PPA repository outside launchpad like:
deb https://download.01.org/gfx/ubuntu/14.04/main Ubuntu 13.10
deb http://apt.tvheadend.org/stable trusty main
deb http://liveusb.info/multisystem/depot all main

**Comment by brennanhm** [comment]
@muzena Thanks for your feedback :)
Currently I'm trying to work out all the kinks to get it working efficiently and reliably with PPAs that are hosted on Launchpad. Once that's finished, I'll see what I can do about PPAs that are hosted elsewhere.

**Comment by brennanhm** [comment]
I looked into fetching the changelog for PPA packages that are not hosted on Launchpad, but without a standard URL, directory path and file naming convention, it doesn't seem feasible at this time.

As it stands, both /etc/apt/sources.list and /etc/apt/sources.list.d/ are scanned for the PPA package's owner and name. If found, an attempt is made to fetch the debian tarball and extract the changelog. If unable to get the changelog from the tarball, the latest changelog entry is scraped from Launchpad's website. 

Thanks to Eduard Dopler for his ideas and feedback throughout the process.

**Comment by brennanhm** [comment]
I've added this to [my PPA](https://launchpad.net/~brennanhm/+archive/ubuntu/linuxmint) for anyone who would like to try it out.

**Comment by muzena** [comment]
@brennanhm Works good, but only for Launchpad repositories.

**Comment by muzena** [comment]
@brennanhm 
Please, can you fix merge conflicts.

**Comment by clefebvre** [comment]
Hi,

No need to rebase.

**Comment by clefebvre** [comment]
Et voila, it's in. Many thanks @brennanhm ;)

**Comment by brennanhm** [comment]
Thank you :)

**Comment by clefebvre** [comment]
Thanks :)

**Pull request merged**
