### PR TITLE
Initial Repository pull

### PR DESCRIPTION
**Pull request by dnessett**
Get repository from local host

### CODE REVIEW

**Comment by rcalixte** [comment]
@dnessett As a note, you don't need to write custom scripts for this. There is an entire mature package for this: [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades). There are also many articles and blog posts online with how to use this service as well.

**Comment by dnessett** [comment]
> @dnessett As a note, you don't need to write custom scripts for this. There is an entire mature package for this: [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades). There are also many articles and blog posts online with how to use this service as well.

While this is a useful package, it doesn't do what I need nor what I think other admins of LM farms need. Specifically, if I understand correctly, this package will continually update packages as they are released. In managing the farm of LM laptops under my control, I don't want automatic updates. To ensure stability, I want to control when updates occur. In my case, I would like to limit those updates to those that are part of an OS release. Right now I am concentrating on updating the laptops when a minor release comes out. I would like to also upgrade the laptops when a major release is available, but that appears to be a much harder problem to solve.

Anyway, thanks for the suggestion.

**Comment by rcalixte** [comment]
> To ensure stability, I want to control when updates occur.

It's configurable to your needs. Having a mature tool that you spend time learning instead of custom scripts is most likely the best long-term route.

**Comment by dnessett** [comment]
> > To ensure stability, I want to control when updates occur.
> 
> It's configurable to your needs. Having a mature tool that you spend time learning instead of custom scripts is most likely the best long-term route.

So it is clear, I am not managing one or two LM systems. I am managing 30. I use the SALT distributed application management system.  In terms of features, I want something that changes the version of the OS for all 30 systems at once, not something that updates arbitrary packages.

**Comment by rcalixte** [comment]
> I want something that changes the version of the OS for all 30 systems at once

You want to manage major updates? That would be managing the apt configuration files. That is linked, along with documentation for cron if you want precise scheduling. All of that should be configurable with Salt states. Please let me know if there's anything I've misunderstood.

**Comment by dnessett** [comment]
> > I want something that changes the version of the OS for all 30 systems at once
> 
> You want to manage major updates? That would be managing the apt configuration files. That is linked, along with documentation for cron if you want precise scheduling. All of that should be configurable with Salt states. Please let me know if there's anything I've misunderstood.

As I mentioned in a previous comment, I am concentrating on minor OS versions at present. Whether it is possible to upgrade the major OS version of the laptops using this approach is an open question, which I am not addressing at this point. Maybe it is and maybe it isn't. Right now I am only working on minor releases.

By the way, I forked linuxmint/mintupdate only to gain access to its code. I have no intention of pushing anything back to this repository. I have created an independent repository in my personal space that I will use to develop the non-interactive mintupdate functionality.

**Comment by rcalixte** [comment]
> I am concentrating on minor OS versions at present.

The same applies. You would manage the apt configuration files and if you want precision for when/how the updates take place, you would configure cron as well. All of this is possible with Salt states and depending on your experience with it, trivial to deploy. There may already be blog posts or articles that you can apply/adopt with minimal modifications.

Minor OS updates would mean just modifying the Mint-based apt entries and leaving the Debian/Ubuntu-based configurations alone. I would strongly encourage getting familiar with some of the underlying system configuration files and the services you can leverage to make your life significantly easier.

**Comment by dnessett** [comment]
I have been working with some knowledgeable developers on [Linux Mint Forums -> Scripts and Bash](https://forums.linuxmint.com/viewtopic.php?t=424287). You may wish to read the content in that thread.

**Comment by rcalixte** [comment]
> You may wish to read the content in that thread.

The focus seems to be on the scripting and the CLI components. I'm suggesting you take a different route entirely with the goal of making your long-term life a lot easier.

**Comment by dnessett** [comment]
> > You may wish to read the content in that thread.
> 
> The focus seems to be on the scripting and the CLI components. I'm suggesting you take a different route entirely with the goal of making your long-term life a lot easier.

I am always open to an approach that would make my long-term life a lot easier, but I don't understand how using [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) would accomplish that.  It would help if you would provide a more specific proposal that would make this clearer.

**Comment by rcalixte** [comment]
> I am always open to an approach that would make my long-term life a lot easier, but I don't understand how using [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) would accomplish that.

You would need to accomplish this in tandem with the apt configuration files. Each component handles a specific task. As an example, you could use [Salt states](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pkg.html) in tandem with the [Salt module for APT](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.aptpkg.html) and piece together other pieces to fine tune your desired result.



> It would help if you would provide a more specific proposal that would make this clearer.

I don't have the infrastructure or the time on hand right now unfortunately. The best I can offer at the moment is the [further reading](https://wiki.debian.org/UnattendedUpgrades#See_Also) that I think will assist you in this.

**Pull request closed without merging**
